### ISSUE TITLE
let is a reserved identifier

### ISSUE THREAD

**Issue by zacharysierakowski** [sindresorhus/copy-text-to-clipboard#17] opened 2018-03-30 12:40 UTC
Could you add babel to bundle up a dist of some sort with the transpiled source? In older versions of firefox, the error `let is a reserved identifier` prevents the webpage from loading entirely. For now, I have been pointing my transpiler into my `node_modules/copy-text-to-clipboard` but, that's not expected behavior.

Alternatively, could you change the source from `let` to `var` please?

**Comment by kevva** [comment] 2018-03-30 18:37
Sort of a duplicate of https://github.com/sindresorhus/copy-text-to-clipboard/issues/5.

**Closed as completed by kevva** 2018-03-30 18:37 UTC
